//AutoGenerated:
import 'package:json_annotation/json_annotation.dart';
import './location.dart';
part 'event.g.dart';

@JsonSerializable(nullable: false)
class Event {
  final String id;
  final String eventName;
  final int startTime;
  final Map<String, bool> attendance;
  final Location location;
  Event({this.id, this.eventName, this.startTime, this.location, this.attendance});
  factory Event.fromJson(Map<String, dynamic> json) => _$EventFromJson(json);
  Map<String, dynamic> toJson() => _$EventToJson(this);
}
