//AutoGenerated:
import 'package:json_annotation/json_annotation.dart';
part 'event.g.dart';

@JsonSerializable(nullable: false)
class Event {
  final String id;
  final String eventName;
  final int startTime;
  final Map<String, bool> attendance;
  final String street;
  final String city;
  final String state;
  final String zip;

  Event(
      {this.id,
      this.eventName,
      this.startTime,
      this.city,
      this.state,
      this.street,
      this.zip,
      this.attendance});

  factory Event.fromJson(Map<String, dynamic> json) => _$EventFromJson(json);

  Map<String, dynamic> toJson() => _$EventToJson(this);
}
