//AutoGenerated:
import 'package:flutter/material.dart';
import 'package:json_annotation/json_annotation.dart';

part 'fire_user.g.dart';

@JsonSerializable(nullable: false)
class FireUser {
  final String uid;
  final String displayName;
  final String isEmailVerified;
  final String phoneNumber;
  final String photoUrl;
  final String providerId;
  final String isAnonymous;
  final String email;
  final String hasProfile;
  final String profile;
  FireUser(
      {this.uid,
      this.displayName,
      this.isEmailVerified,
      this.phoneNumber,
      this.photoUrl,
      this.providerId,
      this.isAnonymous,
      this.email,
      this.hasProfile,
      this.profile});
  factory FireUser.fromJson(Map<String, dynamic> json) =>
      _$FireUserFromJson(json);
  Map<String, dynamic> toJson() => _$FireUserToJson(this);
}
