//AutoGenerated:
import 'package:json_annotation/json_annotation.dart';

part 'location.g.dart';

@JsonSerializable(nullable: false)
class Location {
  final String street;
  final String city;
  final String state;
  final String zip;
  Location(
      {
      this.street,
      this.city,
      this.state,
      this.zip});
  factory Location.fromJson(Map<String, String> json) =>
      _$LocationFromJson(json);
  Map<String, String> toJson() => _$LocationToJson(this);
}
