//AutoGenerated:
import 'package:flutter/material.dart';
import 'package:json_annotation/json_annotation.dart';

part 'location.g.dart';

@JsonSerializable(nullable: false)
class Location {
  final String uid;
  final String address1;
  final String address2;
  final String address3;
  final String city;
  final String state;
  final String zip;
  final String lat;
  final String long;
  Location(
      {this.uid,
      this.address1,
      this.address2,
      this.address3,
      this.city,
      this.state,
      this.zip,
      this.lat,
      this.long});
  factory Location.fromJson(Map<String, dynamic> json) =>
      _$LocationFromJson(json);
  Map<String, dynamic> toJson() => _$LocationToJson(this);
}
