//AutoGenerated:
import 'package:json_annotation/json_annotation.dart';
part 'sermon.g.dart';
@JsonSerializable(nullable: false)
class Sermon {
  final int created;
  final String date;
  final String path;
  final String title;
  final String verse;

  Sermon({this.date, this.path, this.created, this.title, this.verse});

  factory Sermon.fromJson(Map<String, dynamic> json) => _$SermonFromJson(json);
  Map<String, dynamic> toJson() => _$SermonToJson(this);
}
