//AutoGenerated:
import 'package:json_annotation/json_annotation.dart';

part 'user.g.dart';

@JsonSerializable(nullable: false)
class User {
  final String uid;
  final String firstName;
  final String lastName;
  final String email;
  final String dob;
  final String address;
  final String address1;
  final String city;
  final String state;
  final String zip;

  final String role;

  User(
      {this.firstName,
      this.lastName,
      this.email,
      this.dob,
      this.address,
      this.address1,
      this.city,
      this.state,
      this.zip,
      this.uid,
      this.role});

  factory User.fromJson(Map<String, dynamic> json) => _$UserFromJson(json);

  Map<String, dynamic> toJson() => _$UserToJson(this);
}
