//AutoGenerated:
import 'package:flutter/material.dart';
import '../models/event.dart';

class EventProvider {
  Event _event;
  List<Event> _events;
  Map<String, Event> _eventMap;
  Event event(String uid) => _eventMap[uid];
  List<Event> events() => _events;
}
