//AutoGenerated:
import 'package:flutter/material.dart';
import '../models/fire_user.dart';

class FireUserProvider {
  FireUser _fireUser;
  List<FireUser> _fireUsers;
  Map<String, FireUser> _fireUserMap;
  FireUser fireUser(String uid) => _fireUserMap[uid];
  List<FireUser> fireUsers() => _fireUsers;
}
