//AutoGenerated:
import 'package:flutter/material.dart';
import '../models/user.dart';

class UserProvider {
  User _user;
  List<User> _users;
  Map<String, User> _userMap;
  User user(String uid) => _userMap[uid];
  List<User> users() => _users;
}
