//AutoGenerated:
import 'package:flutter/material.dart';
import '../models/location.dart';

class LocationListItemWidget extends StatelessWidget {
  final Location location;
  LocationListItemWidget(this.location);
  @override
  Widget build(context) {
    assert(location != null);
//TODO
    print('complete LocationListItemWidget');
    return Container(child: Text('LocationListItemWidget'));
  }
}

class LocationListWidget extends StatelessWidget {
  final List<Location> locations;
  LocationListWidget(this.locations);
  @override
  Widget build(context) {
    return ListView.builder(
        itemCount: this.locations.length,
        itemBuilder: (BuildContext context, int index) {
          return LocationListItemWidget(this.locations[index]);
        });
  }
}
