//AutoGenerated:
import 'package:flutter/material.dart';
import '../models/profile.dart';

class ProfileListItemWidget extends StatelessWidget {
  final Profile profile;
  ProfileListItemWidget(this.profile);
  @override
  Widget build(context) {
    assert(profile != null);
//TODO
    print('complete ProfileListItemWidget');
    return Container(child: Text('ProfileListItemWidget'));
  }
}

class ProfileListWidget extends StatelessWidget {
  final List<Profile> profiles;
  ProfileListWidget(this.profiles);
  @override
  Widget build(context) {
    return ListView.builder(
        itemCount: this.profiles.length,
        itemBuilder: (BuildContext context, int index) {
          return ProfileListItemWidget(this.profiles[index]);
        });
  }
}
