//AutoGenerated:
import 'package:flutter/material.dart';
import '../models/user.dart';

class UserListItemWidget extends StatelessWidget {
  final User user;
  UserListItemWidget(this.user);
  @override
  Widget build(context) {
    assert(user != null);
//TODO
    print('complete UserListItemWidget');
    return Container(child: Text('UserListItemWidget'));
  }
}

class UserListWidget extends StatelessWidget {
  final List<User> users;
  UserListWidget(this.users);
  @override
  Widget build(context) {
    return ListView.builder(
        itemCount: this.users.length,
        itemBuilder: (BuildContext context, int index) {
          return UserListItemWidget(this.users[index]);
        });
  }
}
