//AutoGenerated:
import 'package:church/src/providers/event_provider.dart';
import 'package:church/src/widgets/bottom_nav.dart';
import 'package:flutter/material.dart';

class EventScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return DefaultTabController(
        length:
        1, //This should be the same as the length of children in TabBarView
        child: Scaffold(
          bottomNavigationBar: BottomNav(currentIndex: 0,),
          body: TabBarView(
            children: [Container(child: Text('EventScreen'))],
          ),
          appBar: AppBar(
            bottom: TabBar(tabs: [Container(child: Text('EventScreen'))]),
            title: null,
            actions: <Widget>[Container(child: Text('EventScreen'))],
          ),
        ));
  }
}

class EventScreenToManyScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return DefaultTabController(
        length:
        1, //This should be the same as the length of children in TabBarView
        child: Scaffold(
          bottomNavigationBar: BottomNav(currentIndex: 0,),
          body: TabBarView(
            children: [Container(child: Text('EventScreen'))],
          ),
          appBar: AppBar(
            bottom: TabBar(tabs: [Container(child: Text('EventScreen'))]),
            title: null,
            actions: <Widget>[Container(child: Text('EventScreen'))],
          ),
        ));
  }
}
