//AutoGenerated:
import 'package:church/src/widgets/bottom_nav.dart';
import 'package:flutter/material.dart';

class LocationScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return DefaultTabController(
        length:
            1, //This should be the same as the length of children in TabBarView
        child: Scaffold(
          bottomNavigationBar: BottomNav(),
          body: TabBarView(
            children: [Container(child: Text('LocationScreen'))],
          ),
          appBar: AppBar(
            bottom: TabBar(tabs: [Container(child: Text('LocationScreen'))]),
            title: null,
            actions: <Widget>[Container(child: Text('LocationScreen'))],
          ),
        ));
  }
}

class LocationScreenToManyScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return DefaultTabController(
        length:
            1, //This should be the same as the length of children in TabBarView
        child: Scaffold(
          bottomNavigationBar: BottomNav(),
          body: TabBarView(
            children: [Container(child: Text('LocationScreen'))],
          ),
          appBar: AppBar(
            bottom: TabBar(tabs: [Container(child: Text('LocationScreen'))]),
            title: null,
            actions: <Widget>[Container(child: Text('LocationScreen'))],
          ),
        ));
  }
}
