//AutoGenerated:
import 'package:church/src/widgets/bottom_nav.dart';
import 'package:flutter/material.dart';

class ProfileScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return DefaultTabController(
        length:
            1, //This should be the same as the length of children in TabBarView
        child: Scaffold(
          bottomNavigationBar: BottomNav(currentIndex: 0,),
          body: TabBarView(
            children: [Container(child: Text('ProfileScreen'))],
          ),
          appBar: AppBar(
            bottom: TabBar(tabs: [Container(child: Text('ProfileScreen'))]),
            title: null,
            actions: <Widget>[Container(child: Text('ProfileScreen'))],
          ),
        ));
  }
}

class ProfileScreenToManyScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return DefaultTabController(
        length:
            1, //This should be the same as the length of children in TabBarView
        child: Scaffold(
          bottomNavigationBar: BottomNav(currentIndex: 0,),
          body: TabBarView(
            children: [Container(child: Text('ProfileScreen'))],
          ),
          appBar: AppBar(
            bottom: TabBar(tabs: [Container(child: Text('ProfileScreen'))]),
            title: null,
            actions: <Widget>[Container(child: Text('ProfileScreen'))],
          ),
        ));
  }
}
