//AutoGenerated:
import 'package:church/factories.dart';
import 'package:church/src/widgets/bottom_nav.dart';
import 'package:flutter/material.dart';

class UserScreen extends StatelessWidget {
  final Factories factories;

  const UserScreen({Key key, @required this.factories}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return DefaultTabController(
        length:
        1, //This should be the same as the length of children in TabBarView
        child: Scaffold(
          bottomNavigationBar: BottomNav(),
          body: TabBarView(
            children: [Container(child: Text('UserScreen'))],
          ),
          appBar: AppBar(
            bottom: TabBar(tabs: [Container(child: Text('UserScreen'))]),
            title: null,
            actions: <Widget>[FlatButton(onPressed: factories.authBloc.signOut, child: Text("Sign Out"),)],
          ),
        ));
  }
}

class UserScreenToManyScreen extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return DefaultTabController(
        length:
        1, //This should be the same as the length of children in TabBarView
        child: Scaffold(
          bottomNavigationBar: BottomNav(),
          body: TabBarView(
            children: [Container(child: Text('UserScreen'))],
          ),
          appBar: AppBar(
            bottom: TabBar(tabs: [Container(child: Text('UserScreen'))]),
            title: null,
            actions: <Widget>[Container(child: Text('UserScreen'))],
          ),
        ));
  }
}
